services:
  app-v1:
    build:
      context: .
    environment:
      - SERVICE_VERSION=0.1.0

  app-v2:
    build:
      context: .
    environment:
      - SERVICE_VERSION=0.2.0

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - V1_PARAMS=${V1_PARAMS:-weight=1}
      - V2_PARAMS=${V2_PARAMS:-backup}
    depends_on:
      - app-v1
      - app-v2
